### ISSUE TITLE
Any chance you could post these in another format like eps?

### ISSUE THREAD

**Issue by BlueByLiquid** [OSCARAdapter/OSCAR#1]
Any chance you could post these in another format like eps?

**Comment by atomcomputing** [comment]
Using an open source program like Inkscape will happily open Corel Draw cdr files.

**Comment by BlueByLiquid** [comment]
Thanks for your quick response. I have tried inkscape's latest version as well as uniconverter (which it uses to convert corel files). This has worked sometimes for me but often not. I didn't have any luck with these specific files. I will see if I can find someone with corel to convert it for me. Thanks
